[package]
name = "hdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix-editor = "0.3.0"
rnix = "0.11.0"
